### ISSUE TITLE
Documentar descontos?

### ISSUE THREAD

**Issue by jgpacker** [brunoventura/wheretolunchlagoa#6]
e.g.

### domo:
desconto: 10%
cartão fidelidade: sim se recusar o desconto
sobremesa: cortesia

### mineiro:
desconto: não
cartão fidelidade: sim
sobremesa: paga

### el grillo:
desconto: 10%
cartão fidelidade: sim, mas só se recusar o desconto e o prêmio é tosco
sobremesa: cortesia

### cantina da freguesia:
desconto: 10%
cartão fidelidade: sim
sobremesa: cortesia

### tempero da ilha (pracinha)
desconto: não
cartão fidelidade: sim, mas o prêmio é café e sobremesa
sobremesa: paga por quilo

### sanduicheria:
desconto: ?
cartão fidelidade: somente para prato feito
sobremesa: não

### lagoa 315
desconto: ?
cartão fidelidade: não
sobremesa: cara

### querubim
desconto: 10%
cartão fidelidade: ?
sobremesa: cortesia

### marques:
desconto: não, porém suco é cortesia
cartão fidelidade: ?
sobremesa: cortesia

**Comment by brunoventura** [comment]
boa @jgpacker !!!
